dist: trusty # use the newer operating system
sudo: false # run our builds in containers
language: go
go:
- 1.11.x
stages:
- name: Testing
- name: Build
jobs:
  include:
  - stage: Testing
    name: Pre-commit
    install:
    - make get
    script:
    - make
  - stage: Build
    name: Build
    install:
    - make get
    script:
    - make build
